### ISSUE TITLE
🩱 Core Team Only All Contributors Bot Add Contributors Here 🩱

### ISSUE THREAD

**Issue by jbampton** [One-Language/Document#1]
https://allcontributors.org/

https://allcontributors.org/docs/en/emoji-key

**Comment by jbampton** [comment]
@all-contributors please add @BaseMax for code

**Comment by jbampton** [comment]
@all-contributors please add @jbampton for projectManagement

**Comment by jbampton** [comment]
@all-contributors please add @all-contributors for doc

**Comment by jbampton** [comment]
@all-contributors please add @amir-shiati for doc

**Comment by jbampton** [comment]
@all-contributors please add @dependabot for maintenance and security

**Comment by jbampton** [comment]
@all-contributors please add @basalumutgazi for ideas, projectManagement and design

**Comment by BaseMax** [comment]
@all-contributors please add @PooiaFerdowsi for doc

**Comment by jbampton** [comment]
@all-contributors please add @johnbampton for review

**Comment by jbampton** [comment]
@all-contributors please add @jbampton for  doc

**Comment by jbampton** [comment]
@all-contributors please add @Monicahinga for projectManagement

**Comment by jbampton** [comment]
@all-contributors please add @basalumutgazi for doc
