### ISSUE TITLE
Fix emoji in translation menu

### ISSUE THREAD

**Issue by jbampton** [One-Language/Document#114]
<img width="232" alt="Screen Shot 2022-10-04 at 2 17 57 am" src="https://user-images.githubusercontent.com/418747/193628045-280cb5f3-465d-4153-a2d7-4c21c1eac1e1.png">

**Comment by ujwalkumar1995** [comment]
Hey. I can submit PR to fix this.

**Comment by jbampton** [comment]
Good to go 👍
