### ISSUE TITLE
Language menu does not fit the content

### ISSUE THREAD

**Issue by jbampton** [One-Language/Document#123]
Drop down language menu does not fit the content on both "Turkish" and "Persian" translations

https://one-lang.pages.dev/#/tr/

<img width="239" alt="Screen Shot 2022-10-04 at 4 09 47 am" src="https://user-images.githubusercontent.com/418747/193648216-60398fa0-051b-44c4-ae0d-fb978eebc3d8.png">

https://one-lang.pages.dev/#/fa/

<img width="143" alt="Screen Shot 2022-10-04 at 2 36 01 am" src="https://user-images.githubusercontent.com/418747/193647792-8650c920-6f6c-4830-a6f2-ea875f599bac.png">

**Comment by Joshua-Nweze** [comment]
Hi @jbampton, please assign me this task, I'll like to work on it

**Comment by jbampton** [comment]
Good to go thanks 👍

**Comment by Joshua-Nweze** [comment]
Good morning,
I have made the changes and created a pull request, this is the link
<https://github.com/One-Language/Document/pull/125>to the pull request.
Please review.
