### ISSUE TITLE
🐛 GitHub Pages CNAME DNS error 🐛

### ISSUE THREAD

**Issue by jbampton** [One-Language/Document#81]
<img width="979" alt="Screen Shot 2022-04-01 at 12 57 11 am" src="https://user-images.githubusercontent.com/418747/161086028-0154fc4b-a425-4296-9baa-a01f6304df33.png">

<img width="818" alt="Screen Shot 2022-04-01 at 12 56 53 am" src="https://user-images.githubusercontent.com/418747/161086038-149e49a6-7e97-4f03-9a58-1ceafa0ff6e8.png">

**Comment by BaseMax** [comment]
hey john
can you say me dns records needed for github pages? I mean server IPs

**Comment by jbampton** [comment]
Hey @BaseMax 

This doc has it all I think

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by BaseMax** [comment]
https://docs.onelang.org/

Thanks, UP AND SSL SAFE!
