### ISSUE TITLE
🐛 `https://run.onelang.org/` is down 🐛

### ISSUE THREAD

**Issue by jbampton** [One-Language/Document#87]
<img width="895" alt="Screen Shot 2022-07-26 at 12 35 57 pm" src="https://user-images.githubusercontent.com/418747/180910962-b28169a5-e244-4494-b2b7-3903ef961a16.png">

**Comment by BaseMax** [comment]
`run` subdomain added and DNS points to `185.199.108.153` (github pages server)

**Comment by BaseMax** [comment]
UP AND LIVE: https://run.onelang.org/
